### PR TITLE
Add build system

### PR DESCRIPTION
**Pull request by gaearon**
This adds `package.json` and Webpack-powered build system.

For building, run `./build.sh`.  
It runs `npm run build` and `npm run build-min` and outputs gzipped file size after minification.

The result files are in `dist` folder in UMD format.

We can later extend this to add examples with watcher, if desired.

### CODE REVIEW

**Comment by gaearon** [comment]
Note I'm not adding ES6 (via 6to5) here. Let's see if this suits your purposes first. If all is fine, I'll add 6to5 in a separate commit.

**Comment by iamralpht** [comment]
Awesome! I'm not using any ES6 features yet nor planning on it, so we can leave 6to5 for now. Thanks for doing this :).

**Comment by gaearon** [comment]
Please check if exports work properly. I haven't put this in test project yet..

**Comment by iamralpht** [comment]
The Gravitas object is exported, so everything's working. I just tried it in the Slalom example. I need to pull in all of the gravitas samples from the physics post at some point.

**Comment by gaearon** [comment]
OK, let me know if I can help you getting examples running in this repo.
Basically we can put them in `examples` folder and give them their own Webpack config with watcher.

**Pull request merged**
